'use client';
import {
  PS_BRAND,
  PS_DIMENSIONS,
  PS_HISTORY,
  PS_ACHILLES,
  PS_ROADMAP,
  PS_SIGNALS,
  PS_SOURCES,
} from '@/lib/data';
import type { Dimension } from '@/lib/types';

function RepDimBar({ d }: { d: Dimension }) {
  const col =
    d.score >= 78 ? 'var(--paper-ok)' : d.score >= 65 ? 'var(--paper-info)' : d.score >= 55 ? 'var(--paper-warn)' : 'var(--paper-bad)';
  return (
    <div className="rep-dim">
      <div className="v" style={{ color: col }}>
        {d.score}
      </div>
      <div className="bar">
        <i style={{ width: `${d.score}%`, background: col }} />
      </div>
      <div className="l">{d.label}</div>
    </div>
  );
}

export function ReportView() {
  const data = PS_HISTORY;
  const w = 670,
    h = 180,
    pad = 28;
  const x = (i: number) => pad + (i / (data.length - 1)) * (w - pad * 2);
  const y = (v: number) => 14 + (h - 40) - ((v - 55) / 35) * (h - 40);
  const line = data
    .map((d, i) => `${i ? 'L' : 'M'}${x(i).toFixed(1)} ${y(d.score).toFixed(1)}`)
    .join(' ');
  const heelSignals = (id: string) => (PS_SIGNALS[id] || [])[0];

  return (
    <div className="report-frame">
      <div>
        <div className="page">
          <div className="rep-head">
            <div className="rep-logo">
              <div className="lg">A</div>
              <div>
                <div className="wm">Project Signal</div>
                <div className="by">by Wayne Strydom</div>
              </div>
            </div>
            <div className="rep-meta">
              WEEKLY BRAND REPORT
              <br />
              Cadence · Challenger bank
              <br />
              {PS_BRAND.period}
              <br />
              Confidential
            </div>
          </div>

          <div className="rep-title">Brand perception is recovering</div>
          <div className="rep-sub">
            Composite index up 4 points to 73 this period, led by Trust and Value — though Service
            remains the weak point after April&apos;s support incident.
          </div>

          <div className="rep-section">
            <h2>Executive summary</h2>
            <div className="rep-score-row">
              <div>
                <div className="rep-score-big" style={{ color: 'var(--paper-ok)' }}>
                  73
                </div>
                <div style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--ink-5)' }}>
                  BRAND PERCEPTION INDEX · +4 pts
                </div>
              </div>
              <div className="rep-dims" style={{ flex: 1 }}>
                {PS_DIMENSIONS.map((d) => (
                  <RepDimBar key={d.key} d={d} />
                ))}
              </div>
            </div>
            <p className="rep-prose" style={{ marginTop: 20 }}>
              Cadence&apos;s perception strengthened across four of five dimensions this period. The
              standout drivers were <b>fee-free spending abroad</b> and <b>transparent pricing</b>,
              both heavily advocated on Trustpilot and YouTube. The single material drag remains{' '}
              <b>support responsiveness</b>, where multi-day waits on account-locked cases continue
              to surface across review platforms. A sharp anomaly was detected six hours ago as
              Service sentiment fell 15 points against its 30-day baseline.
            </p>
          </div>

          <div className="rep-section">
            <h2>Index trend · 26 weeks</h2>
            <svg viewBox={`0 0 ${w} ${h}`} width="100%" style={{ display: 'block' }}>
              {[55, 65, 75, 85].map((t) => (
                <g key={t}>
                  <line x1={pad} x2={w - pad} y1={y(t)} y2={y(t)} stroke="var(--paper-line)" />
                  <text
                    x={pad - 6}
                    y={y(t) + 3}
                    textAnchor="end"
                    style={{ fontFamily: 'var(--font-mono)', fontSize: 9, fill: 'var(--ink-7)' }}
                  >
                    {t}
                  </text>
                </g>
              ))}
              <path
                d={`${line} L${x(data.length - 1)} ${y(55)} L${x(0)} ${y(55)} Z`}
                fill="rgba(31,138,91,0.08)"
              />
              <path
                d={line}
                fill="none"
                stroke="var(--paper-ok)"
                strokeWidth="2.5"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
              <circle
                cx={x(data.length - 1)}
                cy={y(data[data.length - 1]?.score ?? 73)}
                r="4"
                fill="var(--paper-ok)"
              />
            </svg>
          </div>

          <div className="rep-foot">
            <span>Project Signal · Wayne Strydom</span>
            <span>Generated by Gemini Pro · {PS_BRAND.period}</span>
            <span>Page 1 of 2</span>
          </div>
        </div>

        <div className="page">
          <div className="rep-head">
            <div className="rep-logo">
              <div className="lg">A</div>
              <div>
                <div className="wm">Project Signal</div>
                <div className="by">by Wayne Strydom</div>
              </div>
            </div>
            <div className="rep-meta">
              WEEKLY BRAND REPORT
              <br />
              Cadence · Challenger bank
              <br />
              {PS_BRAND.period}
            </div>
          </div>

          <div className="rep-section" style={{ marginTop: 28 }}>
            <h2>Achilles heel · where the damage is</h2>
            {PS_ACHILLES.map((c, i) => {
              const sig = heelSignals(c.id);
              return (
                <div className="rep-heel" key={c.id}>
                  <div className="rk">{i + 1}</div>
                  <div style={{ flex: 1 }}>
                    <div className="ht">
                      {c.title}{' '}
                      <span
                        style={{
                          fontFamily: 'var(--font-mono)',
                          fontSize: 11,
                          color: 'var(--paper-bad)',
                          fontWeight: 600,
                        }}
                      >
                        · damage {c.damage}
                      </span>
                    </div>
                    <div className="hd">{c.summary}</div>
                    {sig && (
                      <p className="rep-quote">
                        &ldquo;{sig.text}&rdquo; — {sig.author}, {sig.source}
                      </p>
                    )}
                  </div>
                </div>
              );
            })}
          </div>

          <div className="rep-section">
            <h2>Recommended actions</h2>
            {PS_ROADMAP.slice(0, 4).map((a, i) => (
              <div className="rep-action" key={a.id}>
                <span className="n">{i + 1}.</span>
                <div style={{ flex: 1 }}>
                  <div style={{ fontWeight: 600, fontSize: 13.5 }}>{a.title}</div>
                  <div style={{ fontSize: 12, color: 'var(--ink-4)', marginTop: 2 }}>
                    {a.priority} · {PS_DIMENSIONS.find((d) => d.key === a.dimension)?.label} ·
                    effort {a.effort}
                  </div>
                </div>
                <span className="impact">+{a.impact} pts</span>
              </div>
            ))}
          </div>

          <div className="rep-section">
            <h2>Data source coverage</h2>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '10px 22px' }}>
              {Object.keys(PS_SOURCES).map((s) => (
                <div
                  key={s}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: 8,
                    fontSize: 12.5,
                    color: 'var(--ink-2)',
                  }}
                >
                  <span
                    style={{
                      width: 9,
                      height: 9,
                      borderRadius: 3,
                      background: PS_SOURCES[s]?.tone,
                    }}
                  />
                  {PS_SOURCES[s]?.label}
                </div>
              ))}
            </div>
            <p className="rep-prose" style={{ marginTop: 14, fontSize: 12.5, color: 'var(--ink-5)' }}>
              {PS_BRAND.signalsThisWeek.toLocaleString()} signals processed this period across{' '}
              {PS_BRAND.sourcesActive} active sources. Every figure in this report is traceable to a
              source item with timestamp, model version and confidence in the Project Signal audit trail.
            </p>
          </div>

          <div className="rep-foot">
            <span>Project Signal · Wayne Strydom</span>
            <span>Every insight is evidence-linked</span>
            <span>Page 2 of 2</span>
          </div>
        </div>
      </div>
    </div>
  );
}
