'use client';

import { useApi } from '@/hooks/useApi';
import { useBrand } from '@/lib/brand-context';
import {
  DIMENSION_LABELS,
  roundScore,
  toActionCards,
  toDimensionCards,
  toHistory,
  type ApiBrandScore,
  type ApiCluster,
  type ApiDimensionRow,
} from '@/lib/brand-data';
import { ViewState } from '@/components/ViewState';

/**
 * The printable weekly report.
 *
 * WHAT THIS REPLACES. Every figure on this page came from `lib/data.ts` — a fictional bank's
 * index, its dimensions, its history, its topic clusters and a hand-written roadmap — under a
 * footer reading "Generated by Gemini Pro". It was a convincing-looking document about a company
 * that does not exist, and it is the one surface in the product a user would print and hand to
 * somebody who cannot check it.
 *
 * It now renders the tenant's real data, and says plainly when there is none. A report that
 * states "not scored yet" is useful; a report that invents a score is worse than no report.
 *
 * The paper palette is deliberate and stays. A printed page is white in both themes — those
 * tokens are not part of the themed instrument surface and are not repointed.
 */

interface ReportStats {
  signalsThisWeek: number;
  signalsPreviousWeek: number;
  totalSignals: number;
  scoredSignals: number;
  activeSources: number;
  configuredSources: number;
}

/** Long-form date for the report header. */
function formatDate(iso: string | null): string {
  if (!iso) return '—';
  return new Date(iso).toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });
}

/** Band colour for a 0-100 score, on the paper ramp. */
function paperBand(score: number): string {
  if (score >= 70) return 'var(--paper-ok)';
  if (score >= 50) return 'var(--paper-warn)';
  return 'var(--paper-bad)';
}

export function ReportView() {
  const { brandId, selected, error: brandError } = useBrand();

  const score = useApi<ApiBrandScore>(brandId ? `/brands/${brandId}/score` : null);
  const history = useApi<ApiDimensionRow[]>(
    brandId ? `/brands/${brandId}/dimension-scores?days=90` : null,
  );
  const impact = useApi<ApiCluster[]>(brandId ? `/brands/${brandId}/brand-impact` : null);
  const stats = useApi<ReportStats>(brandId ? `/brands/${brandId}/stats` : null);

  const loading = score.loading || history.loading || impact.loading || stats.loading;
  const error = score.error ?? history.error ?? impact.error ?? stats.error ?? brandError;

  const points = history.data ? toHistory(history.data) : [];
  const dimensions = score.data ? toDimensionCards(score.data, score.data.previousDimensions) : [];
  const clusters = impact.data ?? [];
  const actions = toActionCards(clusters);

  /* The reporting window is the range the data actually covers. The old header printed a fixed
     string from the fixture — a plausible-looking window corresponding to nothing. */
  const from = points[0]?.date ?? null;
  const to = points[points.length - 1]?.date ?? score.data?.date ?? null;
  const period = from && to ? `${formatDate(from)} – ${formatDate(to)}` : formatDate(to);

  const index = score.data?.score ?? null;
  const previous = score.data?.previousScore ?? null;
  const delta = index !== null && previous !== null ? roundScore(index - previous) : null;

  /* Sparkline over the composite of each day's dimension scores. Drawn only with at least two
     points — a single point is a dot pretending to be a trend. */
  const series = points
    .map((p) => {
      const values = Object.values(p.scores).filter((v): v is number => typeof v === 'number');
      return values.length ? values.reduce((a, b) => a + b, 0) / values.length : null;
    })
    .filter((v): v is number => v !== null);

  const w = 670;
  const h = 180;
  const pad = 28;
  const min = series.length ? Math.min(...series) : 0;
  const max = series.length ? Math.max(...series) : 100;
  const span = max - min || 1;
  const x = (i: number) => pad + (i / Math.max(series.length - 1, 1)) * (w - pad * 2);
  const y = (v: number) => 14 + (h - 40) - ((v - min) / span) * (h - 40);
  const line = series.map((v, i) => `${i ? 'L' : 'M'}${x(i).toFixed(1)} ${y(v).toFixed(1)}`).join(' ');

  return (
    <ViewState loading={loading} error={error} empty={null}>
      <div className="report-frame">
        <div>
          <div className="page">
            <div className="rep-head">
              <div className="rep-logo">
                <div className="lg">S</div>
                <div>
                  <div className="wm">Project Signal</div>
                  <div className="by">Brand perception report</div>
                </div>
              </div>
              <div className="rep-meta">
                WEEKLY BRAND REPORT
                <br />
                {selected?.name ?? 'No brand selected'}
                <br />
                {period}
              </div>
            </div>

            <h1 className="rep-title">{selected?.name ?? 'Brand'} perception</h1>
            <p className="rep-sub">
              {index === null
                ? 'This brand has not been scored yet.'
                : `Brand Perception Index ${roundScore(index)} out of 100.`}
            </p>

            <div className="rep-section">
              <h2>Headline</h2>
              {index === null ? (
                /* Stated, never implied. An absent rollup is "not scored"; printing 0 would
                   assert uniformly negative sentiment about a real business. */
                <p className="rep-prose">
                  No Brand Perception Index has been calculated for this brand. A score appears
                  once signals have been collected and scored — configure at least one source, and
                  check the brand’s name aliases match how people write about it.
                </p>
              ) : (
                <div className="rep-score-row">
                  <div className="rep-score-big" style={{ color: paperBand(index) }}>
                    {roundScore(index)}
                  </div>
                  <div className="rep-prose">
                    <p style={{ margin: 0 }}>
                      {delta === null
                        ? 'No earlier rollup exists yet, so there is no comparison point.'
                        : `${delta >= 0 ? 'Up' : 'Down'} ${Math.abs(delta)} points against ${formatDate(
                            score.data?.previousDate ?? null,
                          )}.`}
                    </p>
                    {stats.data && (
                      <p style={{ margin: '8px 0 0' }}>
                        Built from {stats.data.scoredSignals.toLocaleString()} scored signal
                        {stats.data.scoredSignals === 1 ? '' : 's'} of{' '}
                        {stats.data.totalSignals.toLocaleString()} collected, across{' '}
                        {stats.data.activeSources} active source
                        {stats.data.activeSources === 1 ? '' : 's'}.
                      </p>
                    )}
                  </div>
                </div>
              )}
            </div>

            {dimensions.length > 0 && (
              <div className="rep-section">
                <h2>Dimensions</h2>
                <div className="rep-dims">
                  {dimensions.map((d) => (
                    <div className="rep-dim" key={d.key}>
                      <div className="v" style={{ color: paperBand(d.score) }}>
                        {roundScore(d.score)}
                      </div>
                      <div className="bar">
                        <i style={{ width: `${d.score}%`, background: paperBand(d.score) }} />
                      </div>
                      <div className="l">{DIMENSION_LABELS[d.key]}</div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {series.length > 1 && (
              <div className="rep-section">
                <h2>Trend</h2>
                <svg width={w} height={h} role="img" aria-label="Index over the reporting period">
                  <path d={line} fill="none" stroke="var(--paper-accent)" strokeWidth="2" />
                </svg>
              </div>
            )}

            <div className="rep-foot">
              <span>Project Signal · {period}</span>
              <span>Page 1 of 2</span>
            </div>
          </div>

          <div className="page">
            <div className="rep-head">
              <div className="rep-logo">
                <div className="lg">S</div>
                <div>
                  <div className="wm">What is driving it</div>
                  <div className="by">{selected?.name ?? 'Brand'}</div>
                </div>
              </div>
              <div className="rep-meta">{period}</div>
            </div>

            <div className="rep-section">
              <h2>Brand impact</h2>
              {clusters.length === 0 ? (
                <p className="rep-prose">
                  No topic cluster has enough negative signal to rank. This is also what you see
                  before any signals have been scored.
                </p>
              ) : (
                clusters.map((c, i) => (
                  <div className="rep-heel" key={c.topic}>
                    <div className="rk">{i + 1}</div>
                    <div>
                      <div className="ht">{c.topic}</div>
                      <div className="hd">
                        {c.volume} signal{c.volume === 1 ? '' : 's'} ·{' '}
                        {c.dimensions.map((d) => DIMENSION_LABELS[d as never] ?? d).join(', ') ||
                          'no dimension tagged'}
                      </div>
                    </div>
                  </div>
                ))
              )}
            </div>

            {actions.length > 0 && (
              <div className="rep-section">
                <h2>Where to focus</h2>
                {actions.map((a, i) => (
                  <div className="rep-action" key={a.topic}>
                    <span className="n">{i + 1}</span>
                    <div>
                      <div style={{ fontWeight: 600 }}>{a.title}</div>
                      <div style={{ fontSize: 12.5, color: 'var(--ink-4)' }}>
                        {a.priority}
                        {a.dimensionLabel ? ` · ${a.dimensionLabel}` : ''}
                      </div>
                    </div>
                    <span className="impact">{a.impactShare}% of damage</span>
                  </div>
                ))}
              </div>
            )}

            <div className="rep-section">
              <h2>Method</h2>
              <p className="rep-prose">
                Each signal is scored from −1 to +1 and mapped onto a 0–100 index, weighted by
                recency and by the model’s confidence. Signals fade on a 90-day half-life rather
                than dropping out of a window. Brand impact ranks subjects by volume × negative
                sentiment × recency.
              </p>
              {stats.data && (
                <p className="rep-prose">
                  {stats.data.signalsThisWeek.toLocaleString()} signal
                  {stats.data.signalsThisWeek === 1 ? '' : 's'} collected this week, against{' '}
                  {stats.data.signalsPreviousWeek.toLocaleString()} the week before.{' '}
                  {stats.data.activeSources} of {stats.data.configuredSources} configured source
                  {stats.data.configuredSources === 1 ? '' : 's'} are active.
                </p>
              )}
            </div>

            <div className="rep-foot">
              <span>Project Signal · {period}</span>
              <span>Page 2 of 2</span>
            </div>
          </div>
        </div>
      </div>
    </ViewState>
  );
}
